package org.firstinspires.ftc.teamcode.subsytems.driverControl;

public enum UserIntent {
    IDLE,
    DRIVE_SWITCH,
    SPEED_SWITCH,
    IMU_RESET,
    MANUAL_DRIVE_NORMAL,
    MANUAL_DRIVE_ADJUSTMENTS,
    MANUAL_SLIDE,
    MANUAL_ELBOW,
    MANUAL_INTAKE,
    MANUAL_DIFFERENTIAL,
    PRESET_SUBMERSIBLE_INTAKE,
    PRESET_DEPOSIT_FRONT_TOP,
    PRESET_DEPOSIT_FRONT_BOTTOM,
    PRESET_DEPOSIT_BACK_TOP,
    PRESET_DEPOSIT_BACK_BOTTOM,
    PRESET_SAFE_DRIVING_POSITION,
}
