package org.firstinspires.ftc.teamcode.robot;

public enum RobotActivityState {
    IDLE,
    TRANSITION_TO_DEPOSIT_FRONT_TOP,
    TRANSITION_TO_DEPOSIT_FRONT_BOTTOM,
    TRANSITION_TO_DEPOSIT_BACK_TOP,
    TRANSITION_TO_DEPOSIT_BACK_BOTTOM,
    TRANSITION_TO_SUBMERSIBLE_INTAKE,
    TRANSITION_TO_SAFE_DRIVING_POSITION,
    MANUAL_DRIVE,
    MANUAL_ARM,
    MANUAL_END_EFFECTOR
}
