package org.firstinspires.ftc.teamcode.teleop.stateModels;

public enum RobotState {
    START,
    DRIVING_TO_SUBMERSIBLE,
    READY_TO_ENTER_SUBMERSIBLE,
    READY_TO_INTAKE_SAMPLE,
    BRINGING_SLIDES_BACK_IN,
    READY_TO_LEAVE_SUBMERSIBLE,
    INTERMEDIATE_DEPOSIT_TO_BUCKET_STATE,
    ELBOW_TO_DEPOSIT_IN_BUCKET,
    READY_TO_DEPOSIT_IN_BUCKET,
    READY_TO_DEPOSIT_TO_HUMAN_PLAYER,
    READY_TO_GRAB_SPECIMEN,
    READY_TO_GO_TO_CLIP_POSITION,
    READY_TO_DEPOSIT_CLIP,
    CLIPPED,
    READY_TO_GO_TO_GRAB_SPECIMEN,
    HANGING
}
